# This is quick action to build apk and share it with artifacts
# It's for convenience and nightly-testing with people
name: Build nightly

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-13, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get exe name
        id: exe_name
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            echo "name=gpth-linux" >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "Windows" ]; then
            echo "name=gpth-windoza.exe" >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "macOS" ]; then
            arch=$(uname -m)
            if [ "$arch" == "arm64" ]; then
              echo "name=gpth-macos-arm64" >> $GITHUB_OUTPUT
            elif [ "$arch" == "x86_64" ]; then
              echo "name=gpth-macos-intel" >> $GITHUB_OUTPUT
            else
              echo "Unknown macOS architecture: $arch" >> $GITHUB_OUTPUT
              exit 1
            fi
          else
            echo "Unknown OS: $RUNNER_OS"
            exit 69
          fi
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - name: Build exe
        run: dart compile exe bin/gpth.dart -o ./${{ steps.exe_name.outputs.name }}
      - name: Upload apk as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpth-nightly-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
          path: ./${{ steps.exe_name.outputs.name }}
          if-no-files-found: error